[package]
name = "theta-lang"
version = "0.1.0"
authors = ["Evan Merlock <vnmrlck@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
clap = { version = "3.0.0", features = ["derive"] }
utf8-chars = "1.0.2"