[package]
name = "theta-compiler"
version = "0.1.0"
authors = ["Evan Merlock <vnmrlck@gmail.com>"]
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
utf8-chars = "1.0.2"
log = "0.4.17"
env_logger = "0.10.0"
tracing = "0.1.37"
theta-types = { path = "../theta_types" }